#!/usr/bin/env node
var Parser = require('node-expat').Parser
var reformat = require('./reformat')

var data = {}
var currentElement = null
var currentIndication = null
var parser = new Parser('UTF-8')
  .on('error', function (error) {
    console.error(error)
    process.exit(1)
  })
  .on('startElement', function (name, attributes) {
    currentElement = name
    if (name === 'sref') {
      if (data[currentIndication]) {
        data[currentIndication].push(attributes.ref)
      } else {
        data[currentIndication] = [attributes.ref]
      }
    }
  })
  .on('text', function (text) {
    if (currentElement === 'CWIndication') {
      if (text.trim().length !== 0) {
        currentIndication = text
      }
    }
  })
  .once('end', function () {
    Object.keys(data).forEach(function (key) {
      var ipcs = data[key].filter(function (ipc) {
        return ipc.length === 14
      })
      if (ipcs.length !== 0) {
        console.log(JSON.stringify([
          key.toLowerCase(),
          ipcs.map(reformat)
        ]))
      }
    })
  })

process.stdin.pipe(parser)
