#!/usr/bin/env node
var fs = require('fs')
var Parser = require('node-expat').Parser

var data = {}
var currentElement = null
var currentIndication = null
var parser = new Parser('UTF-8')
  .on('error', function () {
    console.error(error)
    process.exit(1)
  })
  .on('startElement', function (name, attributes) {
    currentElement = name
    if (name === 'sref') {
      if (data[currentIndication]) {
        data[currentIndication].push(attributes.ref)
      } else {
        data[currentIndication] = [attributes.ref]
      }
    }
  })
  .on('text', function (text) {
    if (currentElement === 'CWIndication') {
      if (text.trim().length !== 0) {
        currentIndication = text
      }
    }
  })
  .once('end', function () {
    console.log(JSON.stringify(data, null, 2))
  })
process.stdin.pipe(parser)
