#!/usr/bin/env node
var flushWriteStream = require('flush-write-stream')
var ndJSON = require('ndjson')
var parse = require('./ipc')
var pump = require('pump')

var data = {}

pump(
  process.stdin,
  ndJSON.parse({strict: true}),
  flushWriteStream.obj(function (line, _, done) {
    var symbol = line[0]
    var description = line[1]
    var parsed = parse(symbol)

    if (!data.hasOwnProperty(parsed.section)) {
      data[parsed.section] = {
        description: description[0],
        children: {}
      }
    }
    var sectionChildren = data[parsed.section].children

    var classString = parsed.class
    if (!sectionChildren.hasOwnProperty(classString)) {
      sectionChildren[classString] = {
        description: description[1],
        children: {}
      }
    }
    var classChildren = sectionChildren[parsed.class].children

    var subclassString = parsed.subclass
    if (!classChildren.hasOwnProperty(subclassString)) {
      classChildren[subclassString] = {
        description: description[2],
        children: {}
      }
    }
    var subclassChildren = classChildren[subclassString].children

    var groupString = parsed.group
    if (!subclassChildren.hasOwnProperty(groupString)) {
      subclassChildren[groupString] = {
        description: description[3],
        children: {}
      }
    }
    var groupChildren = subclassChildren[parsed.group].children

    var subgroupString = parsed.subgroup
    if (!groupChildren.hasOwnProperty(subgroupString)) {
      groupChildren[subgroupString] = description.slice(4)
    }

    done()
  }),
  function (error) {
    if (error) {
      console.error(error)
      process.exit(1)
    }
    console.log(JSON.stringify(data, null, 2))
  }
)
